In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# Exercise 1

In [ ]:
import numpy as np
np_array = np.array( [0, 1, 2, 3] )
# Creating an array with ten elements initialized as zero
np_zero_array = np.zeros(10)

In [ ]:
import numpy as np


a = np.array([1, 2, 3])
b = np.array([[4, 5, 6], [7, 8, 9]])
c = np.add(a, b)

print(c)


[[ 5  7  9]
 [ 8 10 12]]


In [ ]:
import numpy as np


a = np.array([1, 2, 3])
b = np.array([[4, 5, 6], [7, 8, 9]])
c = np.subtract(a, b)

print(c)


[[-3 -3 -3]
 [-6 -6 -6]]


In [ ]:
import numpy as np
def predict(data, w):
  return data.dot(w)
# w is the vector of weights
w = np.array([0.1, 0.2, 0.3])
# matrices as input datasets
data1 = np.array([0.3, 1.5, 2.8])
data2 = np.array([0.5, 0.4, 0.9])
data3 = np.array([2.3, 3.1, 0.5])
data_in = np.array([data1[0],data2[0],data3[0]])
print('Predicted value: $%.2f' % predict(data_in, w) )

Predicted value: $0.82


# Exercise 2

In [ ]:
import pandas as pd
import numpy as np

dataset= pd.read_csv('drive/MyDrive/NT522/Lab1/Ex2.csv', index_col=0)
dataset.rename( columns={0:'ID'}, inplace=True )
df= pd.DataFrame(data=dataset)
print(dataset)

     X   Y   Z
id            
1   78  84  86
5   85  94  97
2   80  83  73
4   96  94  96
3   86  86  83


In [ ]:
df.sort_values(by=['id'])

X   Y   Z
id            
1   78  84  86
2   80  83  73
3   86  86  83
4   96  94  96
5   85  94  97

In [ ]:
df.X

1    78
2    85
3    80
4    96
5    86
Name: X, dtype: int64

In [ ]:
df.head(2)
df.head(2)


X   Y      Z
1  78.0  84  False
2  85.0  94  False

In [ ]:
df[df.Y==86]

X   Y   Z
5  86  86  83

In [ ]:
df_NaN= df
df_NaN.loc[4,'X']= np.nan
df_NaN.loc[3,'Z']= np.nan
print(df_NaN)
print(df_NaN.fillna(0))


      X   Y     Z
1  78.0  84  86.0
2  85.0  94  97.0
3  80.0  83   NaN
4   NaN  94  96.0
5  86.0  86  83.0
      X   Y     Z
1  78.0  84  86.0
2  85.0  94  97.0
3  80.0  83   0.0
4   0.0  94  96.0
5  86.0  86  83.0


In [ ]:
df.Z = (df.Z > 90)


In [ ]:
df

X   Y      Z
id               
1   78  84  False
5   85  94   True
2   80  83  False
4   96  94   True
3   86  86  False

In [ ]:
d1= pd.DataFrame(df, columns =['X','Y'])
d2= pd.DataFrame(df, columns =['Z'])
d3 = pd.merge(d1,d2,left_index=True, right_index=True)
print(d1)
print(d2)
print(d3)

     X   Y
id        
1   78  84
5   85  94
2   80  83
4   96  94
3   86  86
     Z
id    
1   86
5   97
2   73
4   96
3   83
     X   Y   Z
id            
1   78  84  86
5   85  94  97
2   80  83  73
4   96  94  96
3   86  86  83


In [ ]:
df.sort_index()

X   Y   Z
id            
1   78  84  86
2   80  83  73
3   86  86  83
4   96  94  96
5   85  94  97

# Exercise 4

In [ ]:
import numpy as np
import csv 
import re

# Đọc dữ liệu từ tập tin SMSSpamCollection
with open('SMSSpamCollection', 'r') as f:
    messages = f.readlines()

# Chọn chỉ các tin nhắn có từ khoá "buy" và "sex"
keywords = ['buy', 'sex']
messages = [m for m in messages if any(w in m.lower() for w in keywords)]

# Tạo một ma trận đặc trưng
features = np.zeros((len(messages), len(keywords)))
for i, m in enumerate(messages):
    features[i] = [len(re.findall(r'\b{}\b'.format(w), m.lower())) for w in keywords]

# Chuyển đổi nhãn "spam" và "ham" sang giá trị số 1 và 0
labels = np.zeros(len(messages), dtype=int)
for i, m in enumerate(messages):
    if m.startswith('spam'):
        labels[i] = 1
        
# Ghi dữ liệu vào file CSV
data = np.concatenate((features, labels.reshape(-1, 1)), axis=1)
with open('drive/MyDrive/NT522/Lab1/sms_spam_perceptron.csv', 'w', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(keywords + ['label'])  # Ghi header của file CSV
    writer.writerows(data)  # Ghi dữ liệu vào file CSV

In [ ]:
import numpy as np
import pandas as pd
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

# Đọc dữ liệu từ file CSV và tách features và labels
data = pd.read_csv('sms_spam_perceptron.csv')
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

# Chia dữ liệu thành tập huấn luyện và kiểm tra
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

# Tiền xử lý dữ liệu: chuẩn hóa features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Khởi tạo và huấn luyện mô hình SVM
svm = SVC(kernel='linear', C=1.0, random_state=0)
svm.fit(X_train, y_train)

# Đánh giá mô hình trên tập kiểm tra
y_pred = svm.predict(X_test)


print('Misclassified samples: %d' % (y_test != y_pred).sum())
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))


In [ ]:
import numpy as np
import pandas as pd
from sklearn.linear import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

# Đọc dữ liệu từ file CSV và tách features và labels
data = pd.read_csv('sms_spam_perceptron.csv')
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

# Chia dữ liệu thành tập huấn luyện và kiểm tra
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

# Tiền xử lý dữ liệu: chuẩn hóa features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Khởi tạo và huấn luyện mô hình SVM
linear_reg= LinearRegression()
linear_reg.fit(X_train, y_train)

# Đánh giá mô hình trên tập kiểm tra
y_pred = (linear_reg.predict(X_test)>0.5).astype(int)


print('Misclassified samples: %d' % (y_test != y_pred).sum())
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))



# Exercise 6

In [ ]:
import pandas as pd
import numpy as np
from sklearn import *
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

phishing_dataset = np.genfromtxt('Training_Dataset.csv', delimiter=',', 
dtype=np.int32)
samples = phishing_dataset[:,:-1]
targets = phishing_dataset[:, -1]
training_samples, testing_samples, training_targets, testing_targets = train_test_split(samples, targets, test_size=0.2, random_state=0)

log_classifier = LogisticRegression()
log_classifier.fit(training_samples, training_targets)

predictions = log_classifier.predict(testing_samples)
accuracy = 100.0 * accuracy_score(testing_targets, predictions)
print ("Logistic Regression accuracy: " + str(accuracy))


In [ ]:
import pandas as pd
import numpy as np
from sklearn import *
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

phishing_dataset = np.genfromtxt('Training_Dataset.csv', delimiter=',', 
dtype=np.int32)
samples = phishing_dataset[:,:-1]
targets = phishing_dataset[:, -1]

from sklearn.model_selection import train_test_split

training_samples, testing_samples, training_targets, testing_targets = train_test_split(samples, targets, test_size=0.2, random_state=0)

from sklearn import tree 
tree_classifier = tree.DecisionTreeClassifier()
tree_classifier.fit(training_samples, training_targets)


predictions = tree_classifier.predict(testing_samples)
accuracy = 100.0 * accuracy_score(testing_targets, predictions)
print ("Decision Trees accuracy: " + str(accuracy))



# Exercise 7

In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

dataset= pd.read_csv('drive/MyDrive/NT522/Lab1/Phishing_Legitimate_full.csv', index_col=0)

In [19]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

def logistic_function(X, w):
    z = np.dot(X, w)
    return 1 / (1 + np.exp(-z))

def logistic_regression(X_train, y_train, lr=0.01, num_iter=1000):
    ones = np.ones((X_train.shape[0], 1))
    X_train = np.hstack((ones, X_train))
    w = np.zeros(X_train.shape[1])
    for i in range(num_iter):
        y_pred = logistic_function(X_train, w)
        gradient = np.dot(X_train.T, (y_pred - y_train)) / y_train.size
        w -= lr * gradient
    return w
df = pd.read_csv('drive/MyDrive/NT522/Lab1/Phishing_Legitimate_full.csv')

X = df.drop('CLASS_LABEL', axis=1).values
y = df['CLASS_LABEL'].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

w = logistic_regression(X_train, y_train)

ones = np.ones((X_test.shape[0], 1))
X_test = np.hstack((ones, X_test))

y_pred = logistic_function(X_test, w)

y_pred[y_pred >= 0.5] = 1
y_pred[y_pred < 0.5] = 0

accuracy = np.mean(y_pred == y_test)
print('Accuracy:', accuracy)


Accuracy: 0.9865
